services:
  - type: web
    name: erdalkazan-website
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    previewsEnabled: true # Pull Request önizlemelerini etkinleştirir
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: erdalkazan-env
